version: 2
jobs:
  build:
    machine: true
    steps:
     - add_ssh_keys:
          fingerprints:
           - "2c:21:24:0c:a6:62:57:5e:e9:05:02:a2:2a:3f:7d:2d"
     - checkout
     - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
     - run: docker build -t pilar07/holadocker:$CIRCLE_SHA1 .
     - run: docker push pilar07/holadocker:$CIRCLE_SHA1
     - run: ssh -o StrictHostKeyChecking=no root@143.198.234.102 "/bin/bash /root/personal-web/deploy.sh $CIRCLE_SHA1"
