version: 2
jobs:
  build:
    machine: true
    steps:
     - add_ssh_keys:
          fingerprints:
           - "2f:d2:86:da:1e:b8:06:02:59:bb:6d:97:70:e8:bb:d3"
     - checkout
     - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
     - run: docker build -t pilar07/holadocker:$CIRCLE_SHA1 .
     - run: docker push pilar07/holadocker:$CIRCLE_SHA1
     - run: ssh -o StrictHostKeyChecking=no root@143.198.234.102 "/bin/bash /root/personal-web/deploy.sh $CIRCLE_SHA1"
