version: 2
jobs:
  build:
    machine: true
    steps:
     - add_ssh_keys:
          fingerprints:
           - "c1:10:30:2f:33:2f:c5:f6:3f:48:6f:3f:41:b4:b1:66"
     - checkout
     - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
     - run: docker build -t pilar07/holadocker:$CIRCLE_SHA1 .
     - run: docker push pilar07/holadocker:$CIRCLE_SHA1
     - run: ssh -o StrictHostKeyChecking=no root@143.198.234.102 "/bin/bash /root/personal-web/deploy.sh $CIRCLE_SHA1"
